<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Request Demo Ekranı
    |--------------------------------------------------------------------------
    |
    | Aşağıdaki metinler kimlik doğrulama partnership sayfasındaki
    | gösterilebilecek mesajlardır. Bu metinleri uygulamanızın
    | gereksinimlerine göre düzenlemekte özgürsünüz.
    |
    */

    "user-agreement" => '<p dir="ltr" style="line-height:1.7999999999999998;text-align: center;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:italic;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">OwnerClick</span></p>
<p dir="ltr" style="line-height:1.7999999999999998;text-align: center;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">PLATFORM KULLANIM S&Ouml;ZLEŞMESİ</span></p>
<p><br></p>
<ol style="margin-top:0;margin-bottom:0;padding-inline-start:48px;">
    <li aria-level="1" dir="ltr" style="list-style-type:decimal;font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;margin-left: -18pt;padding-left: 4.5pt;">
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">TARAFLAR, AMA&Ccedil; &nbsp;VE S&Ouml;ZLEŞME&rsquo;NİN KONUSU&nbsp;</span></p>
    </li>
</ol>
<p><br></p>
<ol style="margin-top:0;margin-bottom:0;padding-inline-start:48px;">
    <li aria-level="2" dir="ltr" style="list-style-type:decimal;font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;margin-left: -18pt;padding-left: 4.5pt;">
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Bu Platform Kullanım S&ouml;zleşmesi, Apple App Store, Google Play Store, Huawei Mobile Services gibi sanal uygulama mağazalarından OwnerClick uygulamasını indiren veya&nbsp;</span><a href="http://www.ownerclick.com" style="text-decoration:none;"><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#0563c1;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:underline;-webkit-text-decoration-skip:none;text-decoration-skip-ink:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">www.ownerclick.com</span></a><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;sitesinden OwnerClick Platformu&rsquo;na (Platform) &uuml;ye olarak kullanmaya başlayan ger&ccedil;ek ve/veya t&uuml;zel kişiler (Kullanıcı) ile OwnerClick A.Ş. (OwnerClick) arasında aşağıdaki şartlar dahilinde akdedilmiştir.</span></p>
    </li>
    <li aria-level="2" dir="ltr" style="list-style-type:decimal;font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;margin-left: -18pt;padding-left: 4.5pt;">
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Kullanıcıların Platform&rsquo;a kayıt olurken bildirdikleri telefon numaraları (varsa) ve mail adresleri yapılacak bildirimlerde esas alınır. Kullanıcılar adres, mail adresi ve telefon değişikliklerini 3 (&uuml;&ccedil;) g&uuml;n i&ccedil;erisinde OwnerClick&rsquo;e bildirmekle y&uuml;k&uuml;ml&uuml;d&uuml;r. Aksi takdirde bilinen adreslere (telefon, mail v.d.) yapılacak bildirimler ge&ccedil;erli kabul edilir.&nbsp;</span></p>
    </li>
    <li aria-level="2" dir="ltr" style="list-style-type:decimal;font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;margin-left: -18pt;padding-left: 4.5pt;">
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Bu Platform Kullanım S&ouml;zleşmesi&rsquo;nde Kullanıcı ve OwnerClick ayrı ayrı &ldquo;Taraf&rdquo; ve birlikte &ldquo;Taraflar&rdquo; olarak anılacaktır.</span></p>
    </li>
    <li aria-level="2" dir="ltr" style="list-style-type:decimal;font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;margin-left: -18pt;padding-left: 4.5pt;">
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Platform Kullanım S&ouml;zleşmesi&rsquo;nin konusu, Platform i&ccedil;erisinde halihazırda mevcut olup talep dahilinde ya da talep olmaksızın gelişmekte olan ve OwnerClick tarafından Kullanıcıların hizmetine sunulacak her t&uuml;rl&uuml; iş ve işlemin koşullarının tespit edilerek bu hususta Taraflar&rsquo;ın hak ve y&uuml;k&uuml;ml&uuml;l&uuml;klerinin belirlenmesidir.&nbsp;</span></p>
    </li>
    <li aria-level="2" dir="ltr" style="list-style-type:decimal;font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;margin-left: -18pt;padding-left: 4.5pt;">
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">OwnerClick Platformu i&ccedil;erisinde Kullanıcıların bilgisi ve hizmetine sunulan her t&uuml;rl&uuml; Gizlilik Politikası ve Kişisel Verilerin Korunmasına ilişkin Aydınlatma Metni, OwnerClick&rsquo;e Başvuru Formu ve bunlarla sınırlı olmamak &uuml;zere ilgili Kullanıcı tarafından kabul edilen ve onaylanan t&uuml;m s&ouml;zleşmeler, bilgi ve belgeler işbu s&ouml;zleşmenin eki olarak kabul edilmekte olup uyuşmazlık ortaya &ccedil;ıkması halinde birlikte değerlendirilecektir. &nbsp;</span></p>
    </li>
    <li aria-level="2" dir="ltr" style="list-style-type:decimal;font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;margin-left: -18pt;padding-left: 4.5pt;">
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Bu Platform Kullanım S&ouml;zleşmesi, m&uuml;lk sahibi olsun ya da olmasın taşınır ya da taşınmaz herhangi bir mal &uuml;zerinde kurulan kira s&ouml;zleşmesinde Kiraya Veren sıfatını taşıyan ger&ccedil;ek ya da t&uuml;zel kişiler, Avukatlar, Gayrimenkul Uzmanları ve bunlarla sınırlı olmamak &uuml;zere OwnerClick Platformuna &uuml;ye olan Kullanıcılar ile Owner Click arasındaki ilişkilerin d&uuml;zenlenmesini ama&ccedil;lamaktadır. OwnerClick ile Kullanıcı arasındaki ilişkilerde Platform &uuml;zerinden erişilebilen ve Kullanıcı tarafından onaylanmış s&ouml;zleşme ile diğer bilgi ve belgeler esas alınacaktır.&nbsp;</span></p>
    </li>
    <li aria-level="2" dir="ltr" style="list-style-type:decimal;font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;margin-left: -18pt;padding-left: 4.5pt;">
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Kullanıcılar, Uygulama&rsquo;yı mobil cihaz ya da internet sitesi &uuml;zerinden Platform&rsquo;a &uuml;yelik kaydı ger&ccedil;ekleştirerek bu Platform Kullanım S&ouml;zleşmesi&rsquo;ni ve Platform Kullanım S&ouml;zleşmesi&rsquo;nin eki niteliğindeki bilgi ve belgeleri okuyup tamamını onayladığını kabul eder.&nbsp;</span></p>
    </li>
    <li aria-level="2" dir="ltr" style="list-style-type:decimal;font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;margin-left: -18pt;padding-left: 4.5pt;">
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">OwnerClick ve Kullanıcı, Platform &uuml;yeliği s&uuml;resince ve &uuml;yeliği sonlansa dahi bu Platform Kullanım S&ouml;zleşmesi ve eki olarak kabul edilen t&uuml;m bilgi ve belgelere uygun olarak davranmayı kabul, beyan ve taahh&uuml;t eder. Bu Platform Kullanım S&ouml;zleşmesi&rsquo;ni kabul etmeyen Kullanıcı ve ziyaret&ccedil;i Platform&rsquo;u ve Owner Click tarafından sunulan hizmetleri kullanmamalıdır.&nbsp;</span></p>
    </li>
    <li aria-level="2" dir="ltr" style="list-style-type:decimal;font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;margin-left: -18pt;padding-left: 4.5pt;">
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">OwnerClick platformu &uuml;zerinden Kullanıcıların hizmetine sunulan ya da sunulacak olan Boya, Badana, İnşaat, Temizlik, Hukuk gibi hizmetlerin ifası i&ccedil;in her bir işlem &ouml;zelinde işbu s&ouml;zleşmeden ayrı olarak OwnerClick ve Kullanıcı arasında her bir hizmet &ouml;zelinde &ccedil;eşitli hizmet s&ouml;zleşmeleri akdedebilecek ya da Kullanıcı talebi doğrultusunda aracılık hizmeti verilebilecektir. Hizmetlere ilişkin mevzuat h&uuml;k&uuml;mleri saklıdır.&nbsp;</span></p>
    </li>
    <li aria-level="2" dir="ltr" style="list-style-type:decimal;font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;margin-left: -18pt;padding-left: 4.5pt;">
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">OwnerClick&rsquo;in işbu Platform Kullanım S&ouml;zleşmesi ve ekleri &uuml;zerinde dilediği zaman tek taraflı olarak Platform &uuml;zerinde yayınlamak suretiyle değişiklik yapma hakkı saklıdır. Kullanıcı bu değişikliklerin Platform &uuml;zerinde yayınlandığı tarih itibariyle ge&ccedil;erli olacağını kabul, beyan ve taahh&uuml;t eder. S&ouml;zleşmeler ve diğer bilgi ve belgeler &uuml;zerindeki değişiklik ve g&uuml;ncellemeleri takip y&uuml;k&uuml;ml&uuml;l&uuml;ğ&uuml; Kullanıcılar &uuml;zerinde olup, değişiklikler &uuml;zerinde Platform&rsquo;un kullanımına devam edilmesi halinde değişiklikler kabul edilmiş sayılır.&nbsp;</span></p>
    </li>
</ol>
<p><br></p>
<ol start="2" style="margin-top:0;margin-bottom:0;padding-inline-start:48px;">
    <li aria-level="1" dir="ltr" style="list-style-type:decimal;font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;margin-left: -18pt;padding-left: 4.5pt;">
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">PLATFORM KULLANIMINA İLİŞKİN GENEL KOŞULLAR</span></p>
    </li>
</ol>
<p><br></p>
<ol style="margin-top:0;margin-bottom:0;padding-inline-start:48px;">
    <li aria-level="2" dir="ltr" style="list-style-type:decimal;font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;margin-left: -18pt;padding-left: 4.5pt;">
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Platform sanal mağazalar &uuml;zerinden indirilerek ya da web site &uuml;zerinden erişim suretiyle kullanılabilmektedir. &nbsp;</span></p>
    </li>
    <li aria-level="2" dir="ltr" style="list-style-type:decimal;font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;margin-left: -18pt;padding-left: 4.5pt;">
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">OwnerClick ve Kullanıcılar Platform&rsquo;u kullanırken genel ahlaka ve kamu d&uuml;zenine aykırı hareket etmemeyi, su&ccedil; teşkil edecek uygulamalardan ve hareketlerden ka&ccedil;ınmayı kabul, beyan ve taahh&uuml;t ederler.&nbsp;</span></p>
    </li>
    <li aria-level="2" dir="ltr" style="list-style-type:decimal;font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;margin-left: -18pt;padding-left: 4.5pt;">
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Kullanıcı&rsquo;nın 2.2. madde h&uuml;km&uuml;ne aykırı hareketlerinin OwnerClick tarafından tespit edilmesi yahut OwnerClick&rsquo;e bildirilmesi hallerinde OwnerClick&rsquo;in ilgililer hakkında soruşturma, kovuşturma yapılması, dava/icra takibi yapılması amacıyla şikayet ve ilgili mercilere başvuruda bulunma hakkı ve tazminat isteme hakkı saklıdır.&nbsp;</span></p>
    </li>
    <li aria-level="2" dir="ltr" style="list-style-type:decimal;font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;margin-left: -18pt;padding-left: 4.5pt;">
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Kullanıcılar Platform&rsquo;a kayıt esnasında kendileriyle ilgili olarak g&uuml;venilir ve yeterli d&uuml;zeyde bilgi vermekle y&uuml;k&uuml;ml&uuml;d&uuml;r. Verilen bilgilere ilişkin doğabilecek her t&uuml;rl&uuml; sorumluluk Kullanıcı&rsquo;ya ait olup Kullanıcı bu bilgileri g&uuml;ncel tutmakla y&uuml;k&uuml;ml&uuml;d&uuml;r. Bu maddede sayılan hususlara aykırılığın tespiti halinde OwnerClick&rsquo;in bilgi, belge, a&ccedil;ıklama, değişiklik ve d&uuml;zeltme talep etme ve l&uuml;zumu halinde yasal yollara başvuru hakkı saklıdır.&nbsp;</span></p>
    </li>
    <li aria-level="2" dir="ltr" style="list-style-type:decimal;font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;margin-left: -18pt;padding-left: 4.5pt;">
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">OwnerClick herhangi bir gerek&ccedil;e g&ouml;stermeksizin Kullanıcı&rsquo;nın &uuml;yeliğini kabul etmeyebilir, kabul edilmiş &uuml;yeliği sonlandırabilir, erişimi engelleyebilir.&nbsp;</span></p>
    </li>
    <li aria-level="2" dir="ltr" style="list-style-type:decimal;font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;margin-left: -18pt;padding-left: 4.5pt;">
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">OwnerClick bu Platform Kullanım S&ouml;zleşmesi&rsquo;ni hi&ccedil;bir gerek&ccedil;e g&ouml;stermeksizin l&uuml;zumlu g&ouml;rmesi halinde tek taraflı olarak bildirimsiz feshedebilir, kısmen ya da tamamen kullanıma kapatabilir yahut Platform&rsquo;a erişimi sonlandırabilir. &nbsp;</span></p>
    </li>
    <li aria-level="2" dir="ltr" style="list-style-type:decimal;font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;margin-left: -18pt;padding-left: 4.5pt;">
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Kullanıcılar, sisteme girmiş oldukları Kişisel Verilere hukuka uygun olarak eriştiklerini ve bu bilgileri OwnerClick&rsquo;e vermeye salahiyetli olduklarını ve bu bilgilerin OwnerClick tarafından işlenebileceğini kabul, beyan ve taahh&uuml;t etmektedirler. Gizlilik ve Kişisel Verilerin Korunmasına ilişkin s&ouml;zleşmenin eki olarak kabul edilen Gizlilik Politikası h&uuml;k&uuml;mleri saklıdır. &nbsp;</span></p>
    </li>
    <li aria-level="2" dir="ltr" style="list-style-type:decimal;font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;margin-left: -18pt;padding-left: 4.5pt;">
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Kullanıcı, Platforma giriş i&ccedil;in kullandığı kullanıcı adı, mail adresi, sosyal medya hesabı, şifre, pin vs. bilgileri gizli tutmak ve g&uuml;venliğini sağlamakla y&uuml;k&uuml;ml&uuml;d&uuml;r. Kullanıcı&rsquo;nın bu y&uuml;k&uuml;ml&uuml;l&uuml;ğ&uuml;ne aykırı davranışlarından doğabilecek her t&uuml;rl&uuml; zarar ve ziyandan OwnerClick sorumlu tutulamaz. Kullanıcı, kendi kusuru haricinde hesap bilgilerinin ele ge&ccedil;irilmesi, hesaba erişim sağlanamaması gibi hallerde bu durumu derhal OwnerClick&rsquo;e bildirmekle y&uuml;k&uuml;ml&uuml;d&uuml;r.&nbsp;</span></p>
    </li>
    <li aria-level="2" dir="ltr" style="list-style-type:decimal;font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;margin-left: -18pt;padding-left: 4.5pt;">
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Platformu oluşturan ve Platform&rsquo;a ait her t&uuml;rl&uuml; bilgi, belge, yazılım, kod vb. &uuml;zerindeki Fikri M&uuml;lkiyet hakları OwnerClick&rsquo;e aittir.&nbsp;</span></p>
    </li>
    <li aria-level="2" dir="ltr" style="list-style-type:decimal;font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;margin-left: -18pt;padding-left: 4.5pt;">
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Platform i&ccedil;erisinde Kullanıcılar tarafından yayınlanan i&ccedil;eriklere ilişkin her t&uuml;rl&uuml; sorumluluk Kullanıcı&rsquo;ya aittir. OwnerClick&rsquo;in Kullanıcılar tarafından Platform&rsquo;a y&uuml;klenen bilgi ve belgelerin doğruluğunu ve hukuka uygunluğunu denetleme y&uuml;k&uuml;ml&uuml;l&uuml;ğ&uuml; bulunmamaktadır. Hukuka ve s&ouml;zleşmeye aykırı kullanımların tespiti halinde 2.2. madde h&uuml;k&uuml;mleri saklıdır.&nbsp;</span></p>
    </li>
    <li aria-level="2" dir="ltr" style="list-style-type:decimal;font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;margin-left: -18pt;padding-left: 4.5pt;">
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">OwnerClick dilediği zaman hi&ccedil;bir gerek&ccedil;e g&ouml;stermeksizin Platform&rsquo;u kullanıma kapatma hakkına ve yetkisine sahiptir. Kullanıcılar kapatma nedeniyle zarara uğradıkları iddiasıyla herhangi bir talepte bulunamazlar.&nbsp;</span></p>
    </li>
    <li aria-level="2" dir="ltr" style="list-style-type:decimal;font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;margin-left: -18pt;padding-left: 4.5pt;">
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">OwnerClick, Kullanıcılar&rsquo;ına sunmuş olduğu hizmetler kapsamında doğrudan ya da dolaylı vaziyette hi&ccedil;bir taahh&uuml;t altına girmemektedir. OwnerClick&rsquo;in Platform i&ccedil;erisinde sunmuş olduğu hizmetler, site i&ccedil;erisinde yer alan y&ouml;nlendirmeler, site i&ccedil;eriği, Kullanıcılar&rsquo;a sunulan kampanya teklifleri ve bunlarla sınırlı olmamak &uuml;zere OwnerClick&rsquo;in yazılı ve s&ouml;zl&uuml; beyanları taahh&uuml;t olarak kabul edilemez.&nbsp;</span></p>
    </li>
</ol>
<p><br></p>
<ol start="3" style="margin-top:0;margin-bottom:0;padding-inline-start:48px;">
    <li aria-level="1" dir="ltr" style="list-style-type:decimal;font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;margin-left: -18pt;padding-left: 4.5pt;">
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&Uuml;YE OLMA VE KULLANIM &nbsp;</span></p>
    </li>
</ol>
<p><br></p>
<ol style="margin-top:0;margin-bottom:0;padding-inline-start:48px;">
    <li aria-level="2" dir="ltr" style="list-style-type:decimal;font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;margin-left: -18pt;padding-left: 4.5pt;">
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Kullanıcılar, Platform &uuml;zerinden &uuml;yelik kaydı bilgilerini doldurarak Platform&rsquo;a &uuml;ye olur. Kullanıcı&rsquo;nın Platform&rsquo;a &uuml;ye olması ardından s&ouml;zl&uuml; ve/veya yazılı bir kira s&ouml;zleşmesi ile kiraya verdiği/kiraladığı mallara ya da kiralanmasına aracılık ettiği taşınmazlara ilişkin bilgileri ekleyerek Platform &uuml;zerinde taşınmaz kaydı oluşturur. Taşınmaz kaydını oluşturan Kullanıcı bu taşınmazına ilişkin kira ilişkisi kapsamında Kiracı&rsquo;nın bilgileri, kira bedeli ve kira s&uuml;resi gibi bilgileri ekleyerek Platform &uuml;zerinden bir kira ilişkisine ilişkin temel bilgileri i&ccedil;eren ve Kira Kontratı olarak adlandırılan bir belge oluşturur.&nbsp;</span></p>
    </li>
    <li aria-level="2" dir="ltr" style="list-style-type:decimal;font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;margin-left: -18pt;padding-left: 4.5pt;">
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Kullanıcılar Platform kullanımı i&ccedil;in başka kullanıcıları yetkilendirme yapabilecektir. Kendi kullanıcı adları &uuml;zerinden yapacakları yetkilendirmelerin t&uuml;m sorumluluğu yetkilendirme yapan kullanıcılara aittir. OwnerClick&rsquo;in Kullanıcılar&rsquo;ın &ouml;zel olarak yaptıkları yetkilendirmeler &uuml;zerinde denetim ve kontrol y&uuml;k&uuml;ml&uuml;l&uuml;ğ&uuml; bulunmamaktadır.&nbsp;</span></p>
    </li>
    <li aria-level="2" dir="ltr" style="list-style-type:decimal;font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;margin-left: -18pt;padding-left: 4.5pt;">
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">OwnerClick, &uuml;yelik s&uuml;recinde yapacağı değerlendirme sonucu Kullanıcı&rsquo;yı &uuml;yelik haklarından faydalandırabileceği gibi, hi&ccedil;bir gerek&ccedil;e g&ouml;stermeksizin başvuruyu iptal etme hakkına da sahiptir.&nbsp;</span></p>
    </li>
</ol>
<p><br></p>
<ol start="4" style="margin-top:0;margin-bottom:0;padding-inline-start:48px;">
    <li aria-level="1" dir="ltr" style="list-style-type:decimal;font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;margin-left: -18pt;padding-left: 4.5pt;">
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">M&Uuml;CBİR SEBEPLER</span></p>
    </li>
</ol>
<p><br></p>
<ol style="margin-top:0;margin-bottom:0;padding-inline-start:48px;">
    <li aria-level="2" dir="ltr" style="list-style-type:decimal;font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;margin-left: -18pt;padding-left: 4.5pt;">
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">OwnerClick&rsquo;in t&uuml;m &ouml;nlemleri almasına rağmen &ouml;ng&ouml;remediği veya &ouml;ng&ouml;rmesine rağmen &ouml;n&uuml;ne ge&ccedil;emeyeceği siber saldırı, doğal afet, grev, salgın hastalık gibi sebepler m&uuml;cbir sebep olarak kabul edilir. M&uuml;cbir sebepler nedeniyle OwnerClick işbu S&ouml;zleşme&rsquo;den doğan y&uuml;k&uuml;ml&uuml;l&uuml;klerini yerine getirmemesi nedeniyle sorumlu tutulamaz. M&uuml;cbir sebep hallerinin 30 g&uuml;nden fazla s&uuml;rmesi halinde OwnerClick&rsquo;in Platform&rsquo;u erişime kapatma ve/veya S&ouml;zleşme&rsquo;yi feshetme hakkı saklıdır. &nbsp;</span></p>
    </li>
</ol>
<p><br></p>
<ol start="5" style="margin-top:0;margin-bottom:0;padding-inline-start:48px;">
    <li aria-level="1" dir="ltr" style="list-style-type:decimal;font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;margin-left: -18pt;padding-left: 4.5pt;">
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">S&Uuml;RE VE FESİH</span></p>
        <ol style="margin-top:0;margin-bottom:0;padding-inline-start:48px;">
            <li aria-level="2" dir="ltr" style="list-style-type:decimal;font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;margin-left: -54pt;padding-left: 4.5pt;">
                <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Kullanıcılar ve OwnerClick Platform&rsquo;un kullanım sıklığına, erişim sıklığına, erişime a&ccedil;ık ya da kapalı olmasına bakılmaksızın işbu S&ouml;zleşme ve ekleri ile s&uuml;resiz bağlı olacaklardır.&nbsp;</span></p>
            </li>
            <li aria-level="2" dir="ltr" style="list-style-type:decimal;font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;margin-left: -54pt;padding-left: 4.5pt;">
                <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Kullanıcılar diledikleri zaman Platform &uuml;yeliklerini iptal edip Platform&rsquo;u kullanmayı bırakabileceklerdir. &nbsp;Kullanıcı&rsquo;nın peşin &ouml;deme yapmış olması halinde peşin &ouml;deme yapılan s&uuml;re i&ccedil;erisinde Kullanıcı&rsquo;nın cayması halinde cayma tarihine kadar Kullanıcı&rsquo;ya sağlanan indirim ve diğer bedeller Kullanıcı&rsquo;dan mahsup edilerek iade tutarı tespit edilir. Kullanıcılar&rsquo;ın Platform&rsquo;u kullanmayı bırakmaları halinde OwnerClick tarafından sunulan &uuml;cretli hizmetlere ilişkin OwnerClick&rsquo;in talep hakları saklıdır.&nbsp;</span></p>
            </li>
        </ol>
    </li>
</ol>
<p><br></p>
<ol start="6" style="margin-top:0;margin-bottom:0;padding-inline-start:48px;">
    <li aria-level="1" dir="ltr" style="list-style-type:decimal;font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;margin-left: -18pt;padding-left: 4.5pt;">
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">TİCARİ ELEKTRONİK İLETİ</span></p>
        <ol style="margin-top:0;margin-bottom:0;padding-inline-start:48px;">
            <li aria-level="2" dir="ltr" style="list-style-type:decimal;font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;margin-left: -54pt;padding-left: 4.5pt;">
                <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Kullanıcı, işbu S&ouml;zleşme&rsquo;yi onaylayarak OwnerClick &uuml;yelik bilgilerinde yer alan e-posta adresi ve telefon numarası kullanılarak veya Platformlar &uuml;zerinden OwnerClick tarafından y&uuml;r&uuml;t&uuml;len kampanyalar, avantajlar, promosyonlar, &uuml;r&uuml;n ve hizmet tanıtımları, reklam, pazar araştırması anketleri ve diğer m&uuml;şteri memnuniyeti uygulamalarının sunulması, bunlar hakkında bilgi verilmesi dahil olmak &uuml;zere kendisine detaylı bilgi, tanıtım, kampanya, indirim ve promosyon bilgileri i&ccedil;eren iletiler g&ouml;nderilmesine, bu S&ouml;zleşme ve diğer metinlerde belirtilen ama&ccedil;larla kendisi ile iletişime ge&ccedil;ilmesine a&ccedil;ık&ccedil;a onay vermektedir. Kullanıcı, OwnerClick&rsquo;e ait &hellip;&hellip;&hellip;... e-posta adresi &uuml;zerinden OwnerClick ile iletişime ge&ccedil;erek her zaman ticari elektronik ileti almayı reddetme imkanını &uuml;cretsiz olarak kullanabilir. Reddetme hakkını kullanmış olmanız, OwnerClick&rsquo;in tabi olduğu ilgili mevzuat h&uuml;k&uuml;mlerine g&ouml;re Kullanıcılar&rsquo;a g&ouml;nderilmesi zorunlu olan bildirimlerin yapılmasına engel teşkil etmez.</span></p>
            </li>
        </ol>
    </li>
</ol>
<p><br></p>
<ol start="7" style="margin-top:0;margin-bottom:0;padding-inline-start:48px;">
    <li aria-level="1" dir="ltr" style="list-style-type:decimal;font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;margin-left: -18pt;padding-left: 4.5pt;">
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&nbsp;DİĞER HUSUSLAR</span></p>
        <ol style="margin-top:0;margin-bottom:0;padding-inline-start:48px;">
            <li aria-level="2" dir="ltr" style="list-style-type:decimal;font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;margin-left: -54pt;padding-left: 4.5pt;">
                <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Taraflar arası uyuşmazlıklarda işbu S&ouml;zleşme&rsquo;nin uygulanması esastır. Bu Platform Kullanım S&ouml;zleşmesi&rsquo;nde ve eklerinde d&uuml;zenlenmemiş her t&uuml;rl&uuml; uyuşmazlığa genel mevzuat h&uuml;k&uuml;mleri uygulanacaktır.&nbsp;</span></p>
            </li>
            <li aria-level="2" dir="ltr" style="list-style-type:decimal;font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;margin-left: -54pt;padding-left: 4.5pt;">
                <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Taraflar arasında doğabilecek uyuşmazlıklarda OwnerClick&rsquo;in veri tabanlarında tuttuğu elektronik kayıtların, ticari defterlerin ve bilumum bilgi ve belgenin kesin ve m&uuml;nhasır delil teşkil edeceği taraflar arasında kararlaştırılmıştır.&nbsp;</span></p>
            </li>
        </ol>
    </li>
</ol>
<p><br></p>
<ol start="8" style="margin-top:0;margin-bottom:0;padding-inline-start:48px;">
    <li aria-level="1" dir="ltr" style="list-style-type:decimal;font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;margin-left: -18pt;padding-left: 4.5pt;">
        <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Y&Uuml;R&Uuml;RL&Uuml;K&nbsp;</span></p>
        <ol style="margin-top:0;margin-bottom:0;padding-inline-start:48px;">
            <li aria-level="2" dir="ltr" style="list-style-type:decimal;font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;margin-left: -54pt;padding-left: 4.5pt;">
                <p dir="ltr" style="line-height:1.7999999999999998;text-align: justify;margin-top:0pt;margin-bottom:8pt;"><span style="font-size:10pt;font-family:"Palatino Linotype",serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Bu Platform Kullanım S&ouml;zleşmesi Kullanıcı tarafından elektronik olarak onayladığı an itibariyle y&uuml;r&uuml;rl&uuml;ğe girecek ve s&uuml;resiz olarak y&uuml;r&uuml;rl&uuml;kte kalacaktır.&nbsp;</span></p>
            </li>
        </ol>
    </li>
</ol>
<p><br></p>
<p><br></p>
<p><br></p>'
];
