<?php

namespace App\Models;

use App\Scopes\OwnerScope;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Auth;
use SebastianBergmann\Template\Template;

class ContractChange extends Contract
{

    protected $table = 'contract_changes';
    protected $fillable = ['creator_id', 'contract_template_id', 'unit_id', 'rental_price', 'deposit_price', 'rental_currency', 'deposit_currency', 'payment_period', 'payment_account_id', 'guarantor_name', 'guarantor_phone', 'guarantor_identification_number', 'start_date', 'end_date', 'notes', 'terminate_id', 'image', 'file_id', 'status_id'];
    protected $primaryKey = 'id';

    protected $dates = ['start_date', 'end_date'];

    //protected $dateFormat = 'Y-m-d';

    function __construct(array $attributes = [])
    {
        Model::__construct($attributes);
    }

    protected static function booted()
    {
    }

    protected $dispatchesEvents = [];


    public function setStartDateAttribute($value)
    {
        $this->attributes['start_date'] = (Carbon::createFromFormat('Y/m/d', $value))->format('Y/m/d');

    }

    public function setEndDateAttribute($value)
    {
        $this->attributes['end_date'] = (Carbon::createFromFormat('Y/m/d', $value))->format('Y/m/d');

    }

    public function finishSave(array $options)
    {
        Model::finishSave($options); // TODO: Change the autogenerated stub
    }

}
